<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Managed.QuickJs/Managed.QuickJs.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(QuickJsRootLibrary)' == 'true'">
    <TrimmerRootAssembly Include="TranslatedQuickJs" />
  </ItemGroup>
</Project>
