using DotCC.PostProcess.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.Text;
using Shouldly;
using Xunit;

namespace DotCC.PostProcess.Analyzers.Tests;

public sealed partial class AnalyzerTests
{
    private const string ComparisonId = PostProcessAnalyzer.BooleanComparisonId;

    [Fact]
    public async Task Comparison_fix_follows_Cond_inlining_and_preserves_execution()
    {
        using var workspace = new AdhocWorkspace();
        var document = workspace.AddDocument(AddProject(workspace).Id, "Case.cs", SourceText.From("""
            public static class Case {
                public static string Run() {
                    int calls = 0;
                    return Cond.B((DotCC.Libc.CBool)(++calls > 0 ? 0 : 1)) + ":" + calls;
                }
            }
            """));
        var original = await Run(document.Project);
        var inlined = await Apply(document, (await Diagnostics(document)).Single(d => d.Id == CondId));
        var changed = await Apply(inlined, (await Diagnostics(inlined)).Single(d => d.Id == ComparisonId));
        (await Run(changed.Project)).ShouldBe(original);
        (await changed.GetTextAsync(Token)).ToString().ShouldNotContain(" ? ");
        (await Diagnostics(changed)).ShouldBeEmpty();
    }

    [Fact]
    public async Task Single_comparison_fix_handles_nested_conditions_and_preserves_siblings()
    {
        using var workspace = new AdhocWorkspace();
        var document = workspace.AddDocument(AddProject(workspace, helper: false).Id, "Case.cs", SourceText.From("""
            public static class Case {
                public static string Run() {
                    int n = 0;
                    bool a = (((++n > 0 ? 0 : 1) != 0) ? 1 : 0) == 0;
                    bool b = (++n > 0 ? 0 : 1) != 0;
                    return a + ":" + b + ":" + n;
                }
            }
            """));
        var diagnostics = await Diagnostics(document);
        diagnostics.Length.ShouldBe(3);
        var changed = await Apply(document, diagnostics.OrderByDescending(d => d.Location.SourceSpan.Length).First());
        (await Run(changed.Project)).ShouldBe(await Run(document.Project));
        (await Diagnostics(changed)).Count(d => d.Id == ComparisonId).ShouldBe(1);
        (await changed.GetTextAsync(Token)).ToString().ShouldContain("bool b = (++n > 0 ? 0 : 1) != 0;");
    }

    [Theory]
    [InlineData(FixAllScope.Document)]
    [InlineData(FixAllScope.Project)]
    [InlineData(FixAllScope.Solution)]
    public async Task Comparison_fix_all_respects_scope(FixAllScope scope)
    {
        using var workspace = new AdhocWorkspace();
        var first = AddProject(workspace, "First", helper: false);
        var a = workspace.AddDocument(first.Id, "A.cs", SourceText.From("class A { bool X(bool b) => (b ? 0 : 1) != 0; }"));
        var b = workspace.AddDocument(first.Id, "B.cs", SourceText.From("class B { bool X(bool b) => (b ? 1 : 0) == 0; }"));
        var other = AddProject(workspace, "Other", helper: false);
        var c = workspace.AddDocument(other.Id, "C.cs", SourceText.From("class C { bool X(bool b) => (b ? 1 : 0) != 0; }"));
        var solution = await FixAll(workspace.CurrentSolution.GetDocument(a.Id)!, ComparisonId, scope);
        foreach (var document in new[] { a, b, c })
        {
            bool affected = document.Id == a.Id || scope == FixAllScope.Solution || scope == FixAllScope.Project && document.Project.Id == first.Id;
            (await Diagnostics(solution.GetDocument(document.Id)!)).Count(d => d.Id == ComparisonId).ShouldBe(affected ? 0 : 1);
        }
    }

    [Fact]
    public async Task Comparison_diagnostic_honors_suppression_and_observable_source()
    {
        using var workspace = new AdhocWorkspace();
        var document = workspace.AddDocument(AddProject(workspace, helper: false).Id, "Case.g.cs", SourceText.From("""
            // <auto-generated/>
            public static class Case {
                static bool First(bool b) => (b ? 0 : 1) != 0;
            #pragma warning disable DCCPP003
                static bool Second(bool b) => (b ? 0 : 1) != 0;
            #pragma warning restore DCCPP003
                static System.Linq.Expressions.Expression<System.Func<bool, bool>> Tree = b => (b ? 0 : 1) != 0;
            }
            """));
        (await Diagnostics(document)).Length.ShouldBe(1);
        var solution = await FixAll(document, ComparisonId, FixAllScope.Document);
        var changed = solution.GetDocument(document.Id)!;
        (await Diagnostics(changed)).ShouldBeEmpty();
        (await changed.GetTextAsync(Token)).ToString().ShouldContain("Second(bool b) => (b ? 0 : 1) != 0;");
    }
}
