#ifndef BLINK_HOST_FCNTL_CONSTANTS_H
#define BLINK_HOST_FCNTL_CONSTANTS_H
/* Observed Linux x64 C host values; not guest Linux ABI constants. */
#define F_DUPFD (0)
#define F_GETFD (1)
#define F_SETFD (2)
#define F_GETFL (3)
#define F_SETFL (4)
#define F_GETLK (5)
#define F_SETLK (6)
#define F_SETLKW (7)
#define F_RDLCK (0)
#define F_WRLCK (1)
#define F_UNLCK (2)
#define FD_CLOEXEC (1)
#define O_RDONLY (0)
#define O_WRONLY (1)
#define O_RDWR (2)
#define O_ACCMODE (3)
#define O_CREAT (64)
#define O_EXCL (128)
#define O_TRUNC (512)
#define O_APPEND (1024)
#define O_NONBLOCK (2048)
#define O_CLOEXEC (524288)
#define O_NOFOLLOW (131072)
#define O_DIRECTORY (65536)
#define O_NOCTTY (256)
#define O_LARGEFILE (0)
#define O_DSYNC (4096)
#define O_SYNC (1052672)
#define AT_FDCWD (-100)
#define AT_REMOVEDIR (512)
#define AT_SYMLINK_NOFOLLOW (256)
#define AT_EACCESS (512)
#endif
