/* Observed Linux x64/glibc values; verified against native headers. */
#ifndef BLINK_MANAGED_RESOURCE_CONSTANTS_H
#define BLINK_MANAGED_RESOURCE_CONSTANTS_H
#define RLIMIT_CPU (0)
#define RLIMIT_FSIZE (1)
#define RLIMIT_DATA (2)
#define RLIMIT_STACK (3)
#define RLIMIT_CORE (4)
#define RLIMIT_RSS (5)
#define RLIMIT_NPROC (6)
#define RLIMIT_NOFILE (7)
#define RLIMIT_MEMLOCK (8)
#define RLIMIT_AS (9)
#define RLIMIT_LOCKS (10)
#define RLIMIT_SIGPENDING (11)
#define RLIMIT_MSGQUEUE (12)
#define RLIMIT_NICE (13)
#define RLIMIT_RTPRIO (14)
#define RLIMIT_RTTIME (15)
#define RUSAGE_SELF (0)
#define RUSAGE_CHILDREN (-1)
#define PRIO_PROCESS (0)
#define PRIO_PGRP (1)
#define PRIO_USER (2)
#endif
