using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace DotCC;

/// <summary>Layout of generated project source files. Whole functions are indivisible.</summary>
public enum SourceSplit { None, Function, Size }

internal sealed record CSharpFunctionSource(string Name, string Text);

public static partial class Compiler
{
    /// <summary>Write emitted sources and remove obsolete files listed in dotcc's
    /// previous source manifest. Unlisted application files are preserved.</summary>
    public static void WriteCSharpFiles(string directory, IReadOnlyDictionary<string, string> sources)
    {
        const string manifest = "Dotcc.SourceFiles.txt";
        static bool GeneratedName(string name)
        {
            if (name == "Program.cs" || name == "Dotcc.GlobalUsings.g.cs") return true;
            // Accept the old naming scheme too so existing manifests migrate cleanly.
            if (name.StartsWith("Dotcc.Functions.", StringComparison.Ordinal) && name.EndsWith(".g.cs", StringComparison.Ordinal)
                && name.All(c => char.IsAsciiLetterOrDigit(c) || c is '.' or '_')) return true;
            static bool Identifier(string value) => value.Length > 0 && (char.IsAsciiLetter(value[0]) || value[0] == '_')
                && value.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');
            static bool Number(string value) => value.Length > 0 && value.All(char.IsAsciiDigit);
            var parts = name.Split('.');
            return parts.Length is 3 or 4 && Identifier(parts[0]) && parts[^1] == "cs"
                && ((Identifier(parts[1]) && (parts.Length == 3 || Number(parts[2])))
                    || (Number(parts[1]) && (parts.Length == 3 || Identifier(parts[2]))));
        }
        if (!sources.ContainsKey("Program.cs") || sources.Keys.Any(name => !GeneratedName(name)))
            throw new ArgumentException("Expected named dotcc project source files", nameof(sources));
        Directory.CreateDirectory(directory);
        var manifestPath = Path.Combine(directory, manifest);
        var previous = File.Exists(manifestPath) ? File.ReadAllLines(manifestPath) : Array.Empty<string>();
        if (previous.Any(name => !GeneratedName(name)))
            throw new IOException("Invalid generated source manifest: " + manifestPath);
        // Delete obsolete names first: a case-only class rename can refer to
        // the same physical file on case-insensitive filesystems.
        foreach (var name in previous.Except(sources.Keys, StringComparer.Ordinal)) File.Delete(Path.Combine(directory, name));
        foreach (var file in sources) File.WriteAllText(Path.Combine(directory, file.Key), file.Value);
        File.WriteAllLines(manifestPath, sources.Keys.Order(StringComparer.Ordinal));
    }

    private static IReadOnlyDictionary<string, string> SingleSource(string source) =>
        new Dictionary<string, string>(StringComparer.Ordinal) { ["Program.cs"] = source };

    private static void ValidateSourceSplit(SourceSplit split, int splitSize, EmitMode emit)
    {
        if (!Enum.IsDefined(split)) throw new CompileException("unknown source split mode");
        if (splitSize <= 0) throw new CompileException("--split-size must be a positive UTF-8 byte count");
        if (split != SourceSplit.None && emit is not (EmitMode.Csproj or EmitMode.ManagedLib or EmitMode.SharedLib))
            throw new CompileException("--split requires C# project output; set it at link time for objects");
    }

    private static IReadOnlyDictionary<string, string> BuildSourceFiles(string functions,
        IReadOnlyList<CSharpFunctionSource>? parts, string aliases, EmitMode emit, string libraryClass,
        string importsClass, bool importsAreStatic, SourceSplit split, int splitSize,
        Func<string, string, bool, string> shell)
    {
        if (split == SourceSplit.None) return SingleSource(shell(functions, aliases, false));
        if (parts == null) throw new CompileException("Object lacks function boundaries; regenerate objects with this dotcc before splitting");
        bool library = emit is EmitMode.ManagedLib or EmitMode.SharedLib;
        var owner = library ? libraryClass : "DotCcProgram";
        // All fields, constructors and runtime types stay in the shell: partial
        // declaration ordering must never change static initialization order.
        var files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Program.cs"] = shell("", "", true)
        };
        // Canonical pointer aliases can be numerous. Emit them once, in a file
        // containing only global usings, instead of repeating them per function.
        if (!string.IsNullOrWhiteSpace(aliases))
            files["Dotcc.GlobalUsings.g.cs"] = "// <auto-generated/>\n" + string.Join("\n",
                aliases.Split('\n').Where(line => line.Length > 0).Select(line => "global " + line)) + "\n";
        var header = "// <auto-generated/>\n"
            + string.Join("\n", new[] { "System", "System.Globalization", "System.Numerics", "System.IO",
                "System.Runtime.InteropServices", "System.Runtime.CompilerServices", "System.Threading",
                "System.Collections.Generic", "System.Collections.Concurrent", "System.Text", "System.Net", "System.Net.Sockets" }
                .Select(ns => "using " + ns + ";")) + "\n"
            + $"using static Libc;\nusing static DotCcGlobals;\nusing static {owner};\nusing DotCcFunctions = global::{owner};\n"
            + (importsClass.Length == 0 ? "" : $"using static {(importsAreStatic ? "DotCcStaticImports" : "DotCcImports")};\n")
            + (emit == EmitMode.ManagedLib ? "public " : "internal ") + $"static unsafe partial class {owner}\n{{\n";
        const string footer = "\n}\n";
        var group = new StringBuilder();
        int groupBytes = Encoding.UTF8.GetByteCount(header + footer), index = 0;
        string firstName = "";
        var filenames = new HashSet<string>(files.Keys, StringComparer.OrdinalIgnoreCase);
        void Flush()
        {
            if (group.Length == 0) return;
            var member = split == SourceSplit.Function
                ? new string(firstName.TrimStart('@')
                    .Select(c => char.IsAsciiLetterOrDigit(c) || c == '_' ? c : '_').ToArray())
                : $"{index++:D5}";
            var stem = $"{owner.TrimStart('@')}.{member}";
            var filename = stem + ".cs";
            int duplicate = 2;
            // C names are case-sensitive, filenames are not on every host.
            // Keep ordinary names clean and disambiguate only real collisions.
            while (!filenames.Add(filename)) filename = $"{stem}.{duplicate++}.cs";
            files[filename] = header + group + footer;
            group.Clear();
            groupBytes = Encoding.UTF8.GetByteCount(header + footer);
        }
        foreach (var part in parts)
        {
            if (group.Length == 0) firstName = part.Name;
            var method = IndentBlock(part.Text.Replace("static unsafe ",
                library ? "public static unsafe " : "internal static unsafe "), "    ") + "\n\n";
            group.Append(method);
            groupBytes = checked(groupBytes + Encoding.UTF8.GetByteCount(method));
            // Append first, then close on the first crossing. A large method is
            // kept whole even if it exceeds the requested target on its own.
            if (split == SourceSplit.Function || groupBytes > splitSize) Flush();
        }
        Flush();
        return files;
    }
}
