// <auto-generated>
using System.Reflection;

namespace FxResources.Managed.Net.Quic
{
    internal static class SR { }
}
namespace System
{
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.Managed.Net.Quic.SR)));

        /// <summary>Connection aborted by peer ({0}).</summary>
        internal static string @net_quic_connectionaborted => GetResourceString("net_quic_connectionaborted");
        /// <summary>Operation aborted.</summary>
        internal static string @net_quic_operationaborted => GetResourceString("net_quic_operationaborted");
        /// <summary>Reading is not allowed on stream.</summary>
        internal static string @net_quic_reading_notallowed => GetResourceString("net_quic_reading_notallowed");
        /// <summary>Writing has been aborted on the stream.</summary>
        internal static string @net_quic_writing_aborted => GetResourceString("net_quic_writing_aborted");
        /// <summary>Reading has been aborted on the stream.</summary>
        internal static string @net_quic_reading_aborted => GetResourceString("net_quic_reading_aborted");
        /// <summary>Stream aborted by peer ({0}).</summary>
        internal static string @net_quic_streamaborted => GetResourceString("net_quic_streamaborted");
        /// <summary>Managed.Net.Quic is not supported on this platform: {0} For more information see: https://learn.microsoft.com/dotnet/fundamentals/networking/quic/quic-overview#platform-dependencies</summary>
        internal static string @ManagedNetQuic_PlatformNotSupported => GetResourceString("ManagedNetQuic_PlatformNotSupported");
        /// <summary>Writing is not allowed on stream.</summary>
        internal static string @net_quic_writing_notallowed => GetResourceString("net_quic_writing_notallowed");
        /// <summary>'{0}' should be within [0, {1}) range.</summary>
        internal static string @net_quic_in_range => GetResourceString("net_quic_in_range");
        /// <summary>'{0}' must be a power of 2.</summary>
        internal static string @net_quic_power_of_2 => GetResourceString("net_quic_power_of_2");
        /// <summary>'{0}' must be specified to start the listener.</summary>
        internal static string @net_quic_not_null_listener => GetResourceString("net_quic_not_null_listener");
        /// <summary>'{0}' must be specified and contain at least one item to start the listener.</summary>
        internal static string @net_quic_not_null_not_empty_listener => GetResourceString("net_quic_not_null_not_empty_listener");
        /// <summary>'{0}' must be specified to open the connection.</summary>
        internal static string @net_quic_not_null_open_connection => GetResourceString("net_quic_not_null_open_connection");
        /// <summary>'{0}' must be specified to accept the connection.</summary>
        internal static string @net_quic_not_null_accept_connection => GetResourceString("net_quic_not_null_accept_connection");
        /// <summary>Timeout can only be set to 'System.Threading.Timeout.Infinite' or a value &gt; 0.</summary>
        internal static string @net_quic_timeout_use_gt_zero => GetResourceString("net_quic_timeout_use_gt_zero");
        /// <summary>'{0}' in not supported remote endpoint type, expected IP or DNS endpoint."</summary>
        internal static string @net_quic_unsupported_endpoint_type => GetResourceString("net_quic_unsupported_endpoint_type");
        /// <summary>'{0}' must be specified and contain at least one item to establish the connection.</summary>
        internal static string @net_quic_not_null_not_empty_connection => GetResourceString("net_quic_not_null_not_empty_connection");
        /// <summary>Server must provide a certificate in '{0}' or '{1}' or via '{2}' for the connection.</summary>
        internal static string @net_quic_not_null_ceritifcate => GetResourceString("net_quic_not_null_ceritifcate");
        /// <summary>Connection timed out waiting for a response from the peer.</summary>
        internal static string @net_quic_timeout => GetResourceString("net_quic_timeout");
        /// <summary>Connection handshake was canceled due to the configured timeout of {0} seconds elapsing.</summary>
        internal static string @net_quic_handshake_timeout => GetResourceString("net_quic_handshake_timeout");
        /// <summary>'{0}' is not supported by Managed.Net.Quic.</summary>
        internal static string @net_quic_ssl_option => GetResourceString("net_quic_ssl_option");
        /// <summary>The remote certificate was rejected by the provided RemoteCertificateValidationCallback.</summary>
        internal static string @net_quic_cert_custom_validation => GetResourceString("net_quic_cert_custom_validation");
        /// <summary>The remote certificate is invalid because of errors in the certificate chain: {0}</summary>
        internal static string @net_quic_cert_chain_validation => GetResourceString("net_quic_cert_chain_validation");
        /// <summary>An internal error has occurred. {0}</summary>
        internal static string @net_quic_internal_error => GetResourceString("net_quic_internal_error");
        /// <summary>Could not use a TLS version required by Quic. TLS 1.3 may have been disabled in the registry.</summary>
        internal static string @net_quic_tls_version_notsupported => GetResourceString("net_quic_tls_version_notsupported");
        /// <summary>CipherSuitePolicy must specify at least one cipher supported by QUIC.</summary>
        internal static string @net_quic_empty_cipher_suite => GetResourceString("net_quic_empty_cipher_suite");
        /// <summary>QuicConnection is configured to not accept any streams.</summary>
        internal static string @net_quic_accept_not_allowed => GetResourceString("net_quic_accept_not_allowed");
        /// <summary>The server refused the connection.</summary>
        internal static string @net_quic_connection_refused => GetResourceString("net_quic_connection_refused");
        /// <summary>A QUIC protocol error was encountered.</summary>
        internal static string @net_quic_protocol_error => GetResourceString("net_quic_protocol_error");
        /// <summary>A specified application protocol is already in use.</summary>
        internal static string @net_quic_alpn_in_use => GetResourceString("net_quic_alpn_in_use");
        /// <summary>A version negotiation error was encountered.</summary>
        internal static string @net_quic_ver_neg_error => GetResourceString("net_quic_ver_neg_error");
        /// <summary>Application layer protocol negotiation error was encountered.</summary>
        internal static string @net_quic_alpn_neg_error => GetResourceString("net_quic_alpn_neg_error");
        /// <summary>The connection timed out from inactivity.</summary>
        internal static string @net_quic_connection_idle => GetResourceString("net_quic_connection_idle");
        /// <summary>Authentication failed: {0}.</summary>
        internal static string @net_quic_auth => GetResourceString("net_quic_auth");
        /// <summary>This method may not be called when another {0} operation is pending.</summary>
        internal static string @net_io_invalidnestedcall => GetResourceString("net_io_invalidnestedcall");
        /// <summary>Authentication failed because the remote party sent a TLS alert: '{0}'.</summary>
        internal static string @net_auth_tls_alert => GetResourceString("net_auth_tls_alert");
        /// <summary>This method may not be called when writing side was already completed.</summary>
        internal static string @net_writecompleted_invalidcall => GetResourceString("net_writecompleted_invalidcall");
        /// <summary>The AddressFamily {0} is not valid for the {1} end point, use {2} instead.</summary>
        internal static string @net_InvalidAddressFamily => GetResourceString("net_InvalidAddressFamily");
        /// <summary>The supplied {0} is an invalid size for the {1} end point.</summary>
        internal static string @net_InvalidSocketAddressSize => GetResourceString("net_InvalidSocketAddressSize");
        /// <summary>User configured callback failed.</summary>
        internal static string @net_quic_callback_error => GetResourceString("net_quic_callback_error");
        /// <summary>Authentication failed because the platform does not support ephemeral keys.</summary>
        internal static string @net_auth_ephemeral => GetResourceString("net_auth_ephemeral");

    }
}
