<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <Libsmb2GeneratedProject Condition="'$(Libsmb2GeneratedProject)' == ''">$(MSBuildThisFileDirectory)../../generated/TranslatedLibsmb2/TranslatedLibsmb2.csproj</Libsmb2GeneratedProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(Libsmb2GeneratedProject)" />
    <None Update="expected.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
