using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using DotCC.Layout;

namespace DotCC.OffsetGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class OffsetGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Invalid = new DiagnosticDescriptor(
        "DOTCCOFF001", "Invalid dotcc offset metadata", "{0}", "DotCC.Layout", DiagnosticSeverity.Error, true);
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Metadata is embedded in C# so object/link and standalone outputs retain
        // the contract without a sidecar that can be lost during linking.
        var sources = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax,
            static (syntax, cancel) => syntax.Node.SyntaxTree.GetText(cancel).ToString()).Collect();
        context.RegisterSourceOutput(sources, static (output, sources) =>
        {
            try
            {
                var emitted = new SortedDictionary<string, string>(StringComparer.Ordinal);
                foreach (var source in sources)
                foreach (var document in OffsetDocument.ReadSource(source))
                {
                    // Source generation is opt-in; standalone output has identical
                    // declarations in the opposite conditional branch.
                    if (!source.Contains("#if !DOTCC_OFFSET_GENERATOR")) continue;
                    foreach (var request in document.Requests)
                    {
                        var one = new OffsetDocument();
                        foreach (var pair in document.Aggregates) one.Aggregates.Add(pair.Key, pair.Value);
                        one.Requests.Add(request);
                        var declarations = one.Materialize();
                        if (emitted.TryGetValue(request.Name, out var old) && old != declarations)
                            throw new OffsetLayoutException("Conflicting aggregate layouts for " + request.Name);
                        emitted[request.Name] = declarations;
                    }
                }
                foreach (var pair in emitted)
                    output.AddSource(pair.Key + ".g.cs", SourceText.From("// <auto-generated/>\n#if DOTCC_OFFSET_GENERATOR\n" + pair.Value + "#endif\n", Encoding.UTF8));
            }
            catch (Exception exception) when (exception is OffsetLayoutException || exception is FormatException || exception is OverflowException || exception is ArgumentException)
            {
                output.ReportDiagnostic(Diagnostic.Create(Invalid, Location.None, exception.Message));
            }
        });
    }
}
