#!/usr/bin/env python3
"""Generate typed C forwarding declarations from the reviewed host operation inventory."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
spec = json.loads((ROOT / 'config/managed-host/operations.json').read_text())
operations = spec['operations']
header = ['/* Generated by scripts/generate-host-contract.py; edit operations.json. */',
    '#pragma once', '#include "platform_internal.h"', '',
    '#define MSQUIC_HOST_VERSION 1',
    'typedef struct MSQUIC_HOST_TABLE {',
    '    uint32_t Size;', '    uint32_t Version;', '    void* Context;',
    '    uint32_t ProcessorCount;', '    uint64_t TotalMemory;']
wrappers = ['/* Generated typed forwarding code. No default or success callbacks. */',
            '#include "msquic_host_internal.h"', '']
validation = []
for operation in operations:
    name, returns, parameters = operation['name'], operation['returns'], operation['parameters']
    signature = 'void* HostContext' + (', ' + parameters if parameters != 'void' else '')
    header.append(f'    {returns} (*{name})({signature});')
    validation.append(f'    if (!Table->{name}) return QUIC_STATUS_INVALID_PARAMETER;')
    if name in ('CxPlatSystemLoad', 'CxPlatSystemUnload'):
        continue
    arguments = [] if parameters == 'void' else [re.search(r'([A-Za-z_]\w*)$', p.strip()).group(1) for p in parameters.split(',')]
    args = 'Host->Context' + (', ' + ', '.join(arguments) if arguments else '')
    wrappers.extend([f'{returns} {name}({parameters})', '{',
        '    const MSQUIC_HOST_TABLE* Host = MsQuicHostGet();',
        f'    {"return " if returns != "void" else ""}Host->{name}({args});'])
    if name == 'quic_bugcheck':
        wrappers.append('    abort(); /* A returning fatal-error callback cannot resume C execution. */')
    wrappers.extend(['}', ''])
header.extend(['} MSQUIC_HOST_TABLE;', '',
    'QUIC_STATUS MsQuicHostInstall(const MSQUIC_HOST_TABLE* Table);',
    'QUIC_STATUS MsQuicHostUninstall(void);', ''])
out = ROOT / 'src/Host'
(out / 'msquic_host.h').write_text('\n'.join(header))
(out / 'forwarders.c').write_text('\n'.join(wrappers))
(out / 'required_slots.inc').write_text('/* Generated required-slot validation. */\n' + '\n'.join(validation) + '\n')
tests = ['/* Generated test-only fail-fast callbacks; no provider service is simulated. */',
         '#include "msquic_host.h"', '#include <stdio.h>', '']
for operation in operations:
    signature = 'void* HostContext' + (', ' + operation['parameters'] if operation['parameters'] != 'void' else '')
    tests.append(f"static {operation['returns']} Fail_{operation['name']}({signature}) {{ abort(); }}")
tests.extend(['', 'static void Populate(MSQUIC_HOST_TABLE* Table) {',
    '    memset(Table, 0, sizeof(*Table));',
    '    Table->Size = sizeof(*Table); Table->Version = MSQUIC_HOST_VERSION;',
    '    Table->ProcessorCount = 2; Table->TotalMemory = 4294967296ULL;'])
tests.extend(f"    Table->{operation['name']} = Fail_{operation['name']};" for operation in operations)
tests.extend(['}', '', 'static unsigned CheckMissing(MSQUIC_HOST_TABLE* Table) {',
              '    MSQUIC_HOST_TABLE Broken;', '    unsigned Count = 0;'])
for operation in operations:
    tests.extend(['    Broken = *Table;', f"    Broken.{operation['name']} = NULL;",
        '    if (MsQuicHostInstall(&Broken) != QUIC_STATUS_INVALID_PARAMETER) abort();', '    Count++;'])
tests.extend(['    return Count;', '}', ''])
(ROOT / 'tests/HostContract/callbacks.inc').write_text('\n'.join(tests))
print(f'Generated {len(operations)} typed host slots')
