#!/usr/bin/env python3
"""Compare compiler offsetof contracts to native; actual storage needs execution."""
import argparse
import base64
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source", type=pathlib.Path)
args = parser.parse_args()
source = args.source.read_text()
requests = {}
for block in re.findall(r"/\* dotcc-layout-v1\n(.*?)end-dotcc-layout \*/", source, re.S):
    for line in block.splitlines():
        fields = line.split("\t")
        if fields[0] != "request":
            continue
        _, helper, aggregate, member, value = fields
        key = tuple(base64.b64decode(x, validate=True).decode() for x in (aggregate, member))
        request = (helper, int(value))
        if key in requests and requests[key] != request:
            raise SystemExit(f"Conflicting compiler metadata for {key}")
        requests[key] = request

# SQLite's Mem is a typedef of its actual struct tag sqlite3_value.
aliases = {"Mem": "sqlite3_value"}
count = 0
failures = []
for line in (root / "tests/layout-native.expected").read_text().splitlines():
    fields = line.split()
    if not fields or fields[0] != "required":
        continue
    _, aggregate, member, size, alignment, offset, address = fields
    count += 1
    key = (aliases.get(aggregate, aggregate), member)
    if key not in requests:
        failures.append(f"Missing compiler request for {aggregate}.{member}")
        continue
    helper, value = requests[key]
    # Standalone declarations are generated by the same shared layout code as
    # the analyzer. This reads metadata outputs; it does not patch generated C#.
    body = re.search(r"internal static class " + re.escape(helper) + r"\s*\{(.*?)\}", source, re.S)
    if not body:
        failures.append(f"Missing standalone layout contract {helper}")
        continue
    emitted_size = re.search(r"\bSize = (\d+)", body[1])
    emitted_alignment = re.search(r"\bAlignment = (\d+)", body[1])
    if not emitted_size or not emitted_alignment:
        failures.append(f"Incomplete standalone layout contract {helper}")
        continue
    actual = (int(emitted_size[1]), int(emitted_alignment[1]), value)
    expected = (int(size), int(alignment), int(offset))
    if offset != address:
        failures.append(f"Native offset/address mismatch for {aggregate}.{member}")
    if actual != expected:
        failures.append(f"{aggregate}.{member}: native size/alignment/offset {expected}; compiler {actual}")
if not count:
    raise SystemExit("No native offset requests found")
if failures:
    raise SystemExit("\n".join(failures))
print(f"PASS {count} compiler layout contracts match native; emitted storage still requires execution")
