#include "host-bindings.h"
#include "blink/machine.h"
#include "blink/bus.h"
#include <stddef.h>
#if !defined(BLINK_HOST_GUEST_THREADS_H) || !defined(BLINK_MANAGED_SIGNAL_H) || !defined(HAVE_THREADS)
#error Threaded layout requires the exact managed-thread profile
#endif

struct LayoutAlignMachine { char before; struct Machine value; };
struct LayoutAlignSystem { char before; struct System value; };
struct LayoutAlignJit { char before; struct Jit value; };
struct LayoutAlignFd { char before; struct Fd value; };
struct LayoutAlignFds { char before; struct Fds value; };
struct LayoutAlignFutex { char before; struct Futex value; };
struct LayoutAlignFutexes { char before; struct Futexes value; };
struct LayoutAlignBus { char before; struct Bus value; };
struct LayoutAlignFreeList { char before; struct FreeList value; };
struct LayoutAlignPageLocks { char before; struct PageLocks value; };
struct LayoutAlignThreadId { char before; pthread_t value; };
struct LayoutAlignMutex { char before; pthread_mutex_t value; };
struct LayoutAlignCondition { char before; pthread_cond_t value; };
struct LayoutAlignMutexAttribute { char before; pthread_mutexattr_t value; };
struct LayoutAlignConditionAttribute { char before; pthread_condattr_t value; };
struct LayoutAlignOnce { char before; pthread_once_t value; };
struct LayoutAlignSignalSet { char before; sigset_t value; };
struct LayoutAlignSignalJump { char before; blink_host_signal_jump_storage value; };

int ThreadedLayoutCount(void) { return 169; }
const char *ThreadedLayoutName(int index) {
  switch(index) {
    case 0: return "Machine.size";
    case 1: return "Machine.align";
    case 2: return "System.size";
    case 3: return "System.align";
    case 4: return "Jit.size";
    case 5: return "Jit.align";
    case 6: return "Fd.size";
    case 7: return "Fd.align";
    case 8: return "Fds.size";
    case 9: return "Fds.align";
    case 10: return "Futex.size";
    case 11: return "Futex.align";
    case 12: return "Futexes.size";
    case 13: return "Futexes.align";
    case 14: return "Bus.size";
    case 15: return "Bus.align";
    case 16: return "FreeList.size";
    case 17: return "FreeList.align";
    case 18: return "PageLocks.size";
    case 19: return "PageLocks.align";
    case 20: return "ThreadId.size";
    case 21: return "ThreadId.align";
    case 22: return "Mutex.size";
    case 23: return "Mutex.align";
    case 24: return "Condition.size";
    case 25: return "Condition.align";
    case 26: return "MutexAttribute.size";
    case 27: return "MutexAttribute.align";
    case 28: return "ConditionAttribute.size";
    case 29: return "ConditionAttribute.align";
    case 30: return "Once.size";
    case 31: return "Once.align";
    case 32: return "SignalSet.size";
    case 33: return "SignalSet.align";
    case 34: return "SignalJump.size";
    case 35: return "SignalJump.align";
    case 36: return "Machine.ip.offset";
    case 37: return "Machine.ip.width";
    case 38: return "Machine.thread.offset";
    case 39: return "Machine.thread.width";
    case 40: return "Machine.tid.offset";
    case 41: return "Machine.tid.width";
    case 42: return "Machine.system.offset";
    case 43: return "Machine.system.width";
    case 44: return "Machine.attention.offset";
    case 45: return "Machine.attention.width";
    case 46: return "Machine.onhalt.offset";
    case 47: return "Machine.onhalt.width";
    case 48: return "Machine.spawn_sigmask.offset";
    case 49: return "Machine.spawn_sigmask.width";
    case 50: return "Machine.canhalt.offset";
    case 51: return "Machine.canhalt.width";
    case 52: return "Machine.sysdepth.offset";
    case 53: return "Machine.sysdepth.width";
    case 54: return "Machine.sigdepth.offset";
    case 55: return "Machine.sigdepth.width";
    case 56: return "Machine.insyscall.offset";
    case 57: return "Machine.insyscall.width";
    case 58: return "Machine.nofault.offset";
    case 59: return "Machine.nofault.width";
    case 60: return "Machine.freelist.offset";
    case 61: return "Machine.freelist.width";
    case 62: return "Machine.freelist.n.offset";
    case 63: return "Machine.freelist.n.width";
    case 64: return "Machine.pagelocks.offset";
    case 65: return "Machine.pagelocks.width";
    case 66: return "Machine.pagelocks.i.offset";
    case 67: return "Machine.pagelocks.i.width";
    case 68: return "Machine.ctid.offset";
    case 69: return "Machine.ctid.width";
    case 70: return "Machine.signals.offset";
    case 71: return "Machine.signals.width";
    case 72: return "Machine.sigmask.offset";
    case 73: return "Machine.sigmask.width";
    case 74: return "Machine.killed.offset";
    case 75: return "Machine.killed.width";
    case 76: return "Machine.elem.offset";
    case 77: return "Machine.elem.width";
    case 78: return "Machine.xmm.offset";
    case 79: return "Machine.xmm.width";
    case 80: return "Machine.ax.offset";
    case 81: return "Machine.ax.width";
    case 82: return "Machine.fs.base.offset";
    case 83: return "Machine.fs.base.width";
    case 84: return "System.loaded.offset";
    case 85: return "System.loaded.width";
    case 86: return "System.trapexit.offset";
    case 87: return "System.trapexit.width";
    case 88: return "System.exitcode.offset";
    case 89: return "System.exitcode.width";
    case 90: return "System.elf.offset";
    case 91: return "System.elf.width";
    case 92: return "System.elf.interpreter.offset";
    case 93: return "System.elf.interpreter.width";
    case 94: return "System.fds.offset";
    case 95: return "System.fds.width";
    case 96: return "System.machines.offset";
    case 97: return "System.machines.width";
    case 98: return "System.machines_cond.offset";
    case 99: return "System.machines_cond.width";
    case 100: return "System.machines_lock.offset";
    case 101: return "System.machines_lock.width";
    case 102: return "System.pagelocks_cond.offset";
    case 103: return "System.pagelocks_cond.width";
    case 104: return "System.pagelocks_lock.offset";
    case 105: return "System.pagelocks_lock.width";
    case 106: return "System.exec_lock.offset";
    case 107: return "System.exec_lock.width";
    case 108: return "System.sig_lock.offset";
    case 109: return "System.sig_lock.width";
    case 110: return "System.mmap_lock.offset";
    case 111: return "System.mmap_lock.width";
    case 112: return "System.onfilemap.offset";
    case 113: return "System.onfilemap.width";
    case 114: return "System.onbinbase.offset";
    case 115: return "System.onbinbase.width";
    case 116: return "System.redraw.offset";
    case 117: return "System.redraw.width";
    case 118: return "Jit.lock.offset";
    case 119: return "Jit.lock.width";
    case 120: return "Jit.keygen.offset";
    case 121: return "Jit.keygen.width";
    case 122: return "Jit.pagegen.offset";
    case 123: return "Jit.pagegen.width";
    case 124: return "Fd.lock.offset";
    case 125: return "Fd.lock.width";
    case 126: return "Fd.cb.offset";
    case 127: return "Fd.cb.width";
    case 128: return "Fd.path.offset";
    case 129: return "Fd.path.width";
    case 130: return "Fds.list.offset";
    case 131: return "Fds.list.width";
    case 132: return "Fds.lock.offset";
    case 133: return "Fds.lock.width";
    case 134: return "Futex.addr.offset";
    case 135: return "Futex.addr.width";
    case 136: return "Futex.waiters.offset";
    case 137: return "Futex.waiters.width";
    case 138: return "Futex.elem.offset";
    case 139: return "Futex.elem.width";
    case 140: return "Futex.cond.offset";
    case 141: return "Futex.cond.width";
    case 142: return "Futex.lock.offset";
    case 143: return "Futex.lock.width";
    case 144: return "Futexes.active.offset";
    case 145: return "Futexes.active.width";
    case 146: return "Futexes.free.offset";
    case 147: return "Futexes.free.width";
    case 148: return "Futexes.lock.offset";
    case 149: return "Futexes.lock.width";
    case 150: return "Futexes.mem.offset";
    case 151: return "Futexes.mem.width";
    case 152: return "Bus.lock.offset";
    case 153: return "Bus.lock.width";
    case 154: return "Bus.futexes.offset";
    case 155: return "Bus.futexes.width";
    case 156: return "FreeList.n.offset";
    case 157: return "FreeList.n.width";
    case 158: return "FreeList.p.offset";
    case 159: return "FreeList.p.width";
    case 160: return "PageLocks.i.offset";
    case 161: return "PageLocks.i.width";
    case 162: return "PageLocks.n.offset";
    case 163: return "PageLocks.n.width";
    case 164: return "PageLocks.p.offset";
    case 165: return "PageLocks.p.width";
    case 166: return "Bus.lock.stride";
    case 167: return "Futexes.mem.stride";
    case 168: return "Machine.stride";
    default:return "unknown";
  }
}
unsigned long ThreadedLayoutValue(int index) {
  switch(index) {
    case 0: return sizeof(struct Machine);
    case 1: return _Alignof(struct Machine);
    case 2: return sizeof(struct System);
    case 3: return _Alignof(struct System);
    case 4: return sizeof(struct Jit);
    case 5: return _Alignof(struct Jit);
    case 6: return sizeof(struct Fd);
    case 7: return _Alignof(struct Fd);
    case 8: return sizeof(struct Fds);
    case 9: return _Alignof(struct Fds);
    case 10: return sizeof(struct Futex);
    case 11: return _Alignof(struct Futex);
    case 12: return sizeof(struct Futexes);
    case 13: return _Alignof(struct Futexes);
    case 14: return sizeof(struct Bus);
    case 15: return _Alignof(struct Bus);
    case 16: return sizeof(struct FreeList);
    case 17: return _Alignof(struct FreeList);
    case 18: return sizeof(struct PageLocks);
    case 19: return _Alignof(struct PageLocks);
    case 20: return sizeof(pthread_t);
    case 21: return _Alignof(pthread_t);
    case 22: return sizeof(pthread_mutex_t);
    case 23: return _Alignof(pthread_mutex_t);
    case 24: return sizeof(pthread_cond_t);
    case 25: return _Alignof(pthread_cond_t);
    case 26: return sizeof(pthread_mutexattr_t);
    case 27: return _Alignof(pthread_mutexattr_t);
    case 28: return sizeof(pthread_condattr_t);
    case 29: return _Alignof(pthread_condattr_t);
    case 30: return sizeof(pthread_once_t);
    case 31: return _Alignof(pthread_once_t);
    case 32: return sizeof(sigset_t);
    case 33: return _Alignof(sigset_t);
    case 34: return sizeof(blink_host_signal_jump_storage);
    case 35: return _Alignof(blink_host_signal_jump_storage);
    case 36: return offsetof(struct Machine,ip);
    case 37: return sizeof(((struct Machine *)0)->ip);
    case 38: return offsetof(struct Machine,thread);
    case 39: return sizeof(((struct Machine *)0)->thread);
    case 40: return offsetof(struct Machine,tid);
    case 41: return sizeof(((struct Machine *)0)->tid);
    case 42: return offsetof(struct Machine,system);
    case 43: return sizeof(((struct Machine *)0)->system);
    case 44: return offsetof(struct Machine,attention);
    case 45: return sizeof(((struct Machine *)0)->attention);
    case 46: return offsetof(struct Machine,onhalt);
    case 47: return sizeof(((struct Machine *)0)->onhalt);
    case 48: return offsetof(struct Machine,spawn_sigmask);
    case 49: return sizeof(((struct Machine *)0)->spawn_sigmask);
    case 50: return offsetof(struct Machine,canhalt);
    case 51: return sizeof(((struct Machine *)0)->canhalt);
    case 52: return offsetof(struct Machine,sysdepth);
    case 53: return sizeof(((struct Machine *)0)->sysdepth);
    case 54: return offsetof(struct Machine,sigdepth);
    case 55: return sizeof(((struct Machine *)0)->sigdepth);
    case 56: return offsetof(struct Machine,insyscall);
    case 57: return sizeof(((struct Machine *)0)->insyscall);
    case 58: return offsetof(struct Machine,nofault);
    case 59: return sizeof(((struct Machine *)0)->nofault);
    case 60: return offsetof(struct Machine,freelist);
    case 61: return sizeof(((struct Machine *)0)->freelist);
    case 62: return offsetof(struct Machine,freelist.n);
    case 63: return sizeof(((struct Machine *)0)->freelist.n);
    case 64: return offsetof(struct Machine,pagelocks);
    case 65: return sizeof(((struct Machine *)0)->pagelocks);
    case 66: return offsetof(struct Machine,pagelocks.i);
    case 67: return sizeof(((struct Machine *)0)->pagelocks.i);
    case 68: return offsetof(struct Machine,ctid);
    case 69: return sizeof(((struct Machine *)0)->ctid);
    case 70: return offsetof(struct Machine,signals);
    case 71: return sizeof(((struct Machine *)0)->signals);
    case 72: return offsetof(struct Machine,sigmask);
    case 73: return sizeof(((struct Machine *)0)->sigmask);
    case 74: return offsetof(struct Machine,killed);
    case 75: return sizeof(((struct Machine *)0)->killed);
    case 76: return offsetof(struct Machine,elem);
    case 77: return sizeof(((struct Machine *)0)->elem);
    case 78: return offsetof(struct Machine,xmm);
    case 79: return sizeof(((struct Machine *)0)->xmm);
    case 80: return offsetof(struct Machine,ax);
    case 81: return sizeof(((struct Machine *)0)->ax);
    case 82: return offsetof(struct Machine,fs.base);
    case 83: return sizeof(((struct Machine *)0)->fs.base);
    case 84: return offsetof(struct System,loaded);
    case 85: return sizeof(((struct System *)0)->loaded);
    case 86: return offsetof(struct System,trapexit);
    case 87: return sizeof(((struct System *)0)->trapexit);
    case 88: return offsetof(struct System,exitcode);
    case 89: return sizeof(((struct System *)0)->exitcode);
    case 90: return offsetof(struct System,elf);
    case 91: return sizeof(((struct System *)0)->elf);
    case 92: return offsetof(struct System,elf.interpreter);
    case 93: return sizeof(((struct System *)0)->elf.interpreter);
    case 94: return offsetof(struct System,fds);
    case 95: return sizeof(((struct System *)0)->fds);
    case 96: return offsetof(struct System,machines);
    case 97: return sizeof(((struct System *)0)->machines);
    case 98: return offsetof(struct System,machines_cond);
    case 99: return sizeof(((struct System *)0)->machines_cond);
    case 100: return offsetof(struct System,machines_lock);
    case 101: return sizeof(((struct System *)0)->machines_lock);
    case 102: return offsetof(struct System,pagelocks_cond);
    case 103: return sizeof(((struct System *)0)->pagelocks_cond);
    case 104: return offsetof(struct System,pagelocks_lock);
    case 105: return sizeof(((struct System *)0)->pagelocks_lock);
    case 106: return offsetof(struct System,exec_lock);
    case 107: return sizeof(((struct System *)0)->exec_lock);
    case 108: return offsetof(struct System,sig_lock);
    case 109: return sizeof(((struct System *)0)->sig_lock);
    case 110: return offsetof(struct System,mmap_lock);
    case 111: return sizeof(((struct System *)0)->mmap_lock);
    case 112: return offsetof(struct System,onfilemap);
    case 113: return sizeof(((struct System *)0)->onfilemap);
    case 114: return offsetof(struct System,onbinbase);
    case 115: return sizeof(((struct System *)0)->onbinbase);
    case 116: return offsetof(struct System,redraw);
    case 117: return sizeof(((struct System *)0)->redraw);
    case 118: return offsetof(struct Jit,lock);
    case 119: return sizeof(((struct Jit *)0)->lock);
    case 120: return offsetof(struct Jit,keygen);
    case 121: return sizeof(((struct Jit *)0)->keygen);
    case 122: return offsetof(struct Jit,pagegen);
    case 123: return sizeof(((struct Jit *)0)->pagegen);
    case 124: return offsetof(struct Fd,lock);
    case 125: return sizeof(((struct Fd *)0)->lock);
    case 126: return offsetof(struct Fd,cb);
    case 127: return sizeof(((struct Fd *)0)->cb);
    case 128: return offsetof(struct Fd,path);
    case 129: return sizeof(((struct Fd *)0)->path);
    case 130: return offsetof(struct Fds,list);
    case 131: return sizeof(((struct Fds *)0)->list);
    case 132: return offsetof(struct Fds,lock);
    case 133: return sizeof(((struct Fds *)0)->lock);
    case 134: return offsetof(struct Futex,addr);
    case 135: return sizeof(((struct Futex *)0)->addr);
    case 136: return offsetof(struct Futex,waiters);
    case 137: return sizeof(((struct Futex *)0)->waiters);
    case 138: return offsetof(struct Futex,elem);
    case 139: return sizeof(((struct Futex *)0)->elem);
    case 140: return offsetof(struct Futex,cond);
    case 141: return sizeof(((struct Futex *)0)->cond);
    case 142: return offsetof(struct Futex,lock);
    case 143: return sizeof(((struct Futex *)0)->lock);
    case 144: return offsetof(struct Futexes,active);
    case 145: return sizeof(((struct Futexes *)0)->active);
    case 146: return offsetof(struct Futexes,free);
    case 147: return sizeof(((struct Futexes *)0)->free);
    case 148: return offsetof(struct Futexes,lock);
    case 149: return sizeof(((struct Futexes *)0)->lock);
    case 150: return offsetof(struct Futexes,mem);
    case 151: return sizeof(((struct Futexes *)0)->mem);
    case 152: return offsetof(struct Bus,lock);
    case 153: return sizeof(((struct Bus *)0)->lock);
    case 154: return offsetof(struct Bus,futexes);
    case 155: return sizeof(((struct Bus *)0)->futexes);
    case 156: return offsetof(struct FreeList,n);
    case 157: return sizeof(((struct FreeList *)0)->n);
    case 158: return offsetof(struct FreeList,p);
    case 159: return sizeof(((struct FreeList *)0)->p);
    case 160: return offsetof(struct PageLocks,i);
    case 161: return sizeof(((struct PageLocks *)0)->i);
    case 162: return offsetof(struct PageLocks,n);
    case 163: return sizeof(((struct PageLocks *)0)->n);
    case 164: return offsetof(struct PageLocks,p);
    case 165: return sizeof(((struct PageLocks *)0)->p);
    case 166: return sizeof(((struct Bus *)0)->lock[0]);
    case 167: return sizeof(((struct Futexes *)0)->mem[0]);
    case 168: return sizeof(struct Machine);
    default:return (unsigned long)-1;
  }
}

/* Scratch-record byte interoperability only; no Machine lifecycle or execution. */
void ThreadedLayoutWrite(struct Machine *m, struct System *s, struct Bus *b) {
  m->ip=0x123456789abcdef0ULL;m->thread=-37;m->tid=0x1234;m->system=s;
  atomic_store_explicit(&m->attention, true, memory_order_release);
  m->canhalt=true;m->nofault=true;m->insyscall=true;m->sysdepth=3;m->sigdepth=4;
  m->freelist.n=5;m->pagelocks.i=6;m->ctid=0x1020304050LL;m->fs.base=0x6172839405ULL;
  for(int i=0;i<8;++i)m->ax[i]=0x31+i;
  m->onhalt[0].ordinary.words[0]=0x9988776655443322ULL;
  m->onhalt[0].mask_saved=1;m->spawn_sigmask.words[0]=0x12345678;
  s->loaded=true;s->trapexit=true;s->exitcode=33;s->fds.list=&m->elem;
  s->machines_cond=11;s->machines_lock=12;s->pagelocks_cond=13;
  s->pagelocks_lock=14;s->exec_lock=15;s->sig_lock=16;s->mmap_lock=17;
  b->lock[0]=21;b->lock[kBusCount-1]=22;
  b->futexes.mem[0].addr=0x1234000;b->futexes.mem[kFutexMax-1].cond=23;
}
int ThreadedLayoutVerify(struct Machine *m, struct System *s, struct Bus *b) {
  if(m->ip!=0xfedcba9876543210ULL || m->thread!=-73 || m->tid!=0x4321 || m->system!=s)return 1;
  if(atomic_load_explicit(&m->attention,memory_order_acquire) || m->canhalt || m->nofault || m->insyscall)return 2;
  if(m->sysdepth!=7 || m->sigdepth!=8 || m->freelist.n!=9 || m->pagelocks.i!=10)return 3;
  if(m->ctid!=0x5060708090LL || m->fs.base!=0x1728394056ULL)return 4;
  for(int i=0;i<8;++i)if(m->ax[i]!=0x51+i)return 5;
  if(m->onhalt[0].ordinary.words[0]!=0x2233445566778899ULL || m->onhalt[0].mask_saved!=0 ||
     m->spawn_sigmask.words[0]!=0x87654321)return 6;
  if(s->loaded || s->trapexit || s->exitcode!=44 || s->fds.list!=&m->elem)return 7;
  if(s->machines_cond!=31 || s->machines_lock!=32 || s->pagelocks_cond!=33 ||
     s->pagelocks_lock!=34 || s->exec_lock!=35 || s->sig_lock!=36 || s->mmap_lock!=37)return 8;
  if(b->lock[0]!=41 || b->lock[kBusCount-1]!=42 || b->futexes.mem[0].addr!=0x5678000 ||
     b->futexes.mem[kFutexMax-1].cond!=43)return 9;
  return 0;
}
