using global::System;
using global::System.Collections.Generic;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using Blink = Managed.Emulation.BlinkCore;

static unsafe class Program {
    static readonly Dictionary<string, ulong> values = new();
    static readonly List<nint> allocations = new();
    static ulong Width<T>(ref T value) where T : unmanaged => (ulong)sizeof(T);
    static ulong Offset(void* start, void* field) => (ulong)((byte*)field - (byte*)start);
    static T* Allocate<T>() where T : unmanaged {
        nuint length = ((nuint)sizeof(T) * 2 + 15) & ~(nuint)15;
        void* value = NativeMemory.AlignedAlloc(length, 16);
        if (value == null) throw new OutOfMemoryException();
        NativeMemory.Clear(value, length); allocations.Add((nint)value);
        if (((nuint)value & 15) != 0) throw new Exception("Scratch alignment");
        return (T*)value;
    }
    static void Check(string name, ulong actual) {
        if (!values.TryGetValue(name, out ulong expected) || actual != expected)
            throw new Exception($"{name}: actual {actual}, expected {expected}");
    }
    static void Require(bool condition) { if (!condition) throw new Exception("Record sentinel mismatch"); }
    static void Main() {
        try {
            for (int i = 0; i < Blink.ThreadedLayoutCount(); ++i) {
                string name = Marshal.PtrToStringUTF8((nint)Blink.ThreadedLayoutName(i))!;
                ulong value = Blink.ThreadedLayoutValue(i); values.Add(name, value);
                Console.WriteLine($"{name} {value}");
            }
            Require(values.Count == 169);
            Blink.Machine* m = Allocate<Blink.Machine>();
            Check("Machine.size", (ulong)sizeof(Blink.Machine));
            Blink.LayoutAlignMachine alignMachine = default;
            Check("Machine.align", Offset(&alignMachine, &alignMachine.value));
            Blink.System* s = Allocate<Blink.System>();
            Check("System.size", (ulong)sizeof(Blink.System));
            Blink.LayoutAlignSystem alignSystem = default;
            Check("System.align", Offset(&alignSystem, &alignSystem.value));
            Blink.Jit* jit = Allocate<Blink.Jit>();
            Check("Jit.size", (ulong)sizeof(Blink.Jit));
            Blink.LayoutAlignJit alignJit = default;
            Check("Jit.align", Offset(&alignJit, &alignJit.value));
            Blink.Fd* fd = Allocate<Blink.Fd>();
            Check("Fd.size", (ulong)sizeof(Blink.Fd));
            Blink.LayoutAlignFd alignFd = default;
            Check("Fd.align", Offset(&alignFd, &alignFd.value));
            Blink.Fds* fds = Allocate<Blink.Fds>();
            Check("Fds.size", (ulong)sizeof(Blink.Fds));
            Blink.LayoutAlignFds alignFds = default;
            Check("Fds.align", Offset(&alignFds, &alignFds.value));
            Blink.Futex* futex = Allocate<Blink.Futex>();
            Check("Futex.size", (ulong)sizeof(Blink.Futex));
            Blink.LayoutAlignFutex alignFutex = default;
            Check("Futex.align", Offset(&alignFutex, &alignFutex.value));
            Blink.Futexes* futexes = Allocate<Blink.Futexes>();
            Check("Futexes.size", (ulong)sizeof(Blink.Futexes));
            Blink.LayoutAlignFutexes alignFutexes = default;
            Check("Futexes.align", Offset(&alignFutexes, &alignFutexes.value));
            Blink.Bus* bus = Allocate<Blink.Bus>();
            Check("Bus.size", (ulong)sizeof(Blink.Bus));
            Blink.LayoutAlignBus alignBus = default;
            Check("Bus.align", Offset(&alignBus, &alignBus.value));
            Blink.FreeList* list = Allocate<Blink.FreeList>();
            Check("FreeList.size", (ulong)sizeof(Blink.FreeList));
            Blink.LayoutAlignFreeList alignFreeList = default;
            Check("FreeList.align", Offset(&alignFreeList, &alignFreeList.value));
            Blink.PageLocks* locks = Allocate<Blink.PageLocks>();
            Check("PageLocks.size", (ulong)sizeof(Blink.PageLocks));
            Blink.LayoutAlignPageLocks alignPageLocks = default;
            Check("PageLocks.align", Offset(&alignPageLocks, &alignPageLocks.value));
            Blink.LayoutAlignThreadId alignThreadId = default;
            Check("ThreadId.size", Width(ref alignThreadId.value));
            Check("ThreadId.align", Offset(&alignThreadId, &alignThreadId.value));
            Blink.LayoutAlignMutex alignMutex = default;
            Check("Mutex.size", Width(ref alignMutex.value));
            Check("Mutex.align", Offset(&alignMutex, &alignMutex.value));
            Blink.LayoutAlignCondition alignCondition = default;
            Check("Condition.size", Width(ref alignCondition.value));
            Check("Condition.align", Offset(&alignCondition, &alignCondition.value));
            Blink.LayoutAlignMutexAttribute alignMutexAttribute = default;
            Check("MutexAttribute.size", Width(ref alignMutexAttribute.value));
            Check("MutexAttribute.align", Offset(&alignMutexAttribute, &alignMutexAttribute.value));
            Blink.LayoutAlignConditionAttribute alignConditionAttribute = default;
            Check("ConditionAttribute.size", Width(ref alignConditionAttribute.value));
            Check("ConditionAttribute.align", Offset(&alignConditionAttribute, &alignConditionAttribute.value));
            Blink.LayoutAlignOnce alignOnce = default;
            Check("Once.size", Width(ref alignOnce.value));
            Check("Once.align", Offset(&alignOnce, &alignOnce.value));
            Blink.LayoutAlignSignalSet alignSignalSet = default;
            Check("SignalSet.size", Width(ref alignSignalSet.value));
            Check("SignalSet.align", Offset(&alignSignalSet, &alignSignalSet.value));
            Blink.LayoutAlignSignalJump alignSignalJump = default;
            Check("SignalJump.size", Width(ref alignSignalJump.value));
            Check("SignalJump.align", Offset(&alignSignalJump, &alignSignalJump.value));
            Check("Machine.ip.offset", Offset(m, &m->ip));
            Check("Machine.ip.width", Width(ref m->ip));
            Check("Machine.thread.offset", Offset(m, &m->thread));
            Check("Machine.thread.width", Width(ref m->thread));
            Check("Machine.tid.offset", Offset(m, &m->tid));
            Check("Machine.tid.width", Width(ref m->tid));
            Check("Machine.system.offset", Offset(m, &m->blink_host_system));
            Check("Machine.system.width", (ulong)sizeof(nint));
            Check("Machine.attention.offset", Offset(m, &m->attention));
            Check("Machine.attention.width", Width(ref m->attention));
            Check("Machine.onhalt.offset", Offset(m, &m->onhalt));
            Check("Machine.onhalt.width", Width(ref m->onhalt));
            Check("Machine.spawn_sigmask.offset", Offset(m, &m->spawn_sigmask));
            Check("Machine.spawn_sigmask.width", Width(ref m->spawn_sigmask));
            Check("Machine.canhalt.offset", Offset(m, &m->canhalt));
            Check("Machine.canhalt.width", Width(ref m->canhalt));
            Check("Machine.sysdepth.offset", Offset(m, &m->sysdepth));
            Check("Machine.sysdepth.width", Width(ref m->sysdepth));
            Check("Machine.sigdepth.offset", Offset(m, &m->sigdepth));
            Check("Machine.sigdepth.width", Width(ref m->sigdepth));
            Check("Machine.insyscall.offset", Offset(m, &m->insyscall));
            Check("Machine.insyscall.width", Width(ref m->insyscall));
            Check("Machine.nofault.offset", Offset(m, &m->nofault));
            Check("Machine.nofault.width", Width(ref m->nofault));
            Check("Machine.freelist.offset", Offset(m, &m->freelist));
            Check("Machine.freelist.width", Width(ref m->freelist));
            Check("Machine.freelist.n.offset", Offset(m, &m->freelist.n));
            Check("Machine.freelist.n.width", Width(ref m->freelist.n));
            Check("Machine.pagelocks.offset", Offset(m, &m->pagelocks));
            Check("Machine.pagelocks.width", Width(ref m->pagelocks));
            Check("Machine.pagelocks.i.offset", Offset(m, &m->pagelocks.i));
            Check("Machine.pagelocks.i.width", Width(ref m->pagelocks.i));
            Check("Machine.ctid.offset", Offset(m, &m->ctid));
            Check("Machine.ctid.width", Width(ref m->ctid));
            Check("Machine.signals.offset", Offset(m, &m->signals));
            Check("Machine.signals.width", Width(ref m->signals));
            Check("Machine.sigmask.offset", Offset(m, &m->sigmask));
            Check("Machine.sigmask.width", Width(ref m->sigmask));
            Check("Machine.killed.offset", Offset(m, &m->killed));
            Check("Machine.killed.width", Width(ref m->killed));
            Check("Machine.elem.offset", Offset(m, &m->elem));
            Check("Machine.elem.width", Width(ref m->elem));
            Check("Machine.xmm.offset", Offset(m, m->xmm));
            Check("Machine.xmm.width", 256);
            Check("Machine.ax.offset", Offset(m, Blink.GetModrmRegisterWordPointerRead8(m, 3UL << 22, 0, 0)));
            Check("Machine.ax.width", 8);
            Check("Machine.fs.base.offset", Offset(m, Unsafe.AsPointer(ref m->fs.@base)));
            Check("Machine.fs.base.width", Width(ref m->fs.@base));
            Check("System.loaded.offset", Offset(s, &s->loaded));
            Check("System.loaded.width", Width(ref s->loaded));
            Check("System.trapexit.offset", Offset(s, &s->trapexit));
            Check("System.trapexit.width", Width(ref s->trapexit));
            Check("System.exitcode.offset", Offset(s, &s->exitcode));
            Check("System.exitcode.width", Width(ref s->exitcode));
            Check("System.elf.offset", Offset(s, &s->elf));
            Check("System.elf.width", Width(ref s->elf));
            Check("System.elf.interpreter.offset", Offset(s, &s->elf.interpreter));
            Check("System.elf.interpreter.width", (ulong)sizeof(nint));
            Check("System.fds.offset", Offset(s, &s->fds));
            Check("System.fds.width", Width(ref s->fds));
            Check("System.machines.offset", Offset(s, &s->machines));
            Check("System.machines.width", (ulong)sizeof(nint));
            Check("System.machines_cond.offset", Offset(s, &s->machines_cond));
            Check("System.machines_cond.width", Width(ref s->machines_cond));
            Check("System.machines_lock.offset", Offset(s, &s->machines_lock));
            Check("System.machines_lock.width", Width(ref s->machines_lock));
            Check("System.pagelocks_cond.offset", Offset(s, &s->pagelocks_cond));
            Check("System.pagelocks_cond.width", Width(ref s->pagelocks_cond));
            Check("System.pagelocks_lock.offset", Offset(s, &s->pagelocks_lock));
            Check("System.pagelocks_lock.width", Width(ref s->pagelocks_lock));
            Check("System.exec_lock.offset", Offset(s, &s->exec_lock));
            Check("System.exec_lock.width", Width(ref s->exec_lock));
            Check("System.sig_lock.offset", Offset(s, &s->sig_lock));
            Check("System.sig_lock.width", Width(ref s->sig_lock));
            Check("System.mmap_lock.offset", Offset(s, &s->mmap_lock));
            Check("System.mmap_lock.width", Width(ref s->mmap_lock));
            Check("System.onfilemap.offset", Offset(s, &s->onfilemap));
            Check("System.onfilemap.width", (ulong)sizeof(nint));
            Check("System.onbinbase.offset", Offset(s, &s->onbinbase));
            Check("System.onbinbase.width", (ulong)sizeof(nint));
            Check("System.redraw.offset", Offset(s, &s->redraw));
            Check("System.redraw.width", (ulong)sizeof(nint));
            Check("Jit.lock.offset", Offset(jit, &jit->@lock));
            Check("Jit.lock.width", Width(ref jit->@lock));
            Check("Jit.keygen.offset", Offset(jit, &jit->keygen));
            Check("Jit.keygen.width", Width(ref jit->keygen));
            Check("Jit.pagegen.offset", Offset(jit, &jit->pagegen));
            Check("Jit.pagegen.width", Width(ref jit->pagegen));
            Check("Fd.lock.offset", Offset(fd, &fd->@lock));
            Check("Fd.lock.width", Width(ref fd->@lock));
            Check("Fd.cb.offset", Offset(fd, &fd->cb));
            Check("Fd.cb.width", (ulong)sizeof(nint));
            Check("Fd.path.offset", Offset(fd, &fd->path));
            Check("Fd.path.width", (ulong)sizeof(nint));
            Check("Fds.list.offset", Offset(fds, &fds->list));
            Check("Fds.list.width", (ulong)sizeof(nint));
            Check("Fds.lock.offset", Offset(fds, &fds->@lock));
            Check("Fds.lock.width", Width(ref fds->@lock));
            Check("Futex.addr.offset", Offset(futex, &futex->addr));
            Check("Futex.addr.width", Width(ref futex->addr));
            Check("Futex.waiters.offset", Offset(futex, &futex->waiters));
            Check("Futex.waiters.width", Width(ref futex->waiters));
            Check("Futex.elem.offset", Offset(futex, &futex->elem));
            Check("Futex.elem.width", Width(ref futex->elem));
            Check("Futex.cond.offset", Offset(futex, &futex->cond));
            Check("Futex.cond.width", Width(ref futex->cond));
            Check("Futex.lock.offset", Offset(futex, &futex->@lock));
            Check("Futex.lock.width", Width(ref futex->@lock));
            Check("Futexes.active.offset", Offset(futexes, &futexes->active));
            Check("Futexes.active.width", (ulong)sizeof(nint));
            Check("Futexes.free.offset", Offset(futexes, &futexes->free));
            Check("Futexes.free.width", (ulong)sizeof(nint));
            Check("Futexes.lock.offset", Offset(futexes, &futexes->@lock));
            Check("Futexes.lock.width", Width(ref futexes->@lock));
            Check("Futexes.mem.offset", Offset(futexes, &futexes->mem));
            Check("Futexes.mem.width", Width(ref futexes->mem));
            Check("Bus.lock.offset", Offset(bus, bus->@lock));
            Check("Bus.lock.width", (ulong)(256 * sizeof(int)));
            Check("Bus.futexes.offset", Offset(bus, &bus->futexes));
            Check("Bus.futexes.width", Width(ref bus->futexes));
            Check("FreeList.n.offset", Offset(list, &list->n));
            Check("FreeList.n.width", Width(ref list->n));
            Check("FreeList.p.offset", Offset(list, &list->p));
            Check("FreeList.p.width", (ulong)sizeof(nint));
            Check("PageLocks.i.offset", Offset(locks, &locks->i));
            Check("PageLocks.i.width", Width(ref locks->i));
            Check("PageLocks.n.offset", Offset(locks, &locks->n));
            Check("PageLocks.n.width", Width(ref locks->n));
            Check("PageLocks.p.offset", Offset(locks, &locks->p));
            Check("PageLocks.p.width", (ulong)sizeof(nint));
            Check("Bus.lock.stride", Offset(&bus->@lock[0], &bus->@lock[1]));
            Check("Futexes.mem.stride", Offset(&futexes->mem[0], &futexes->mem[1]));
            Check("Machine.stride", Offset(m, m + 1));
            Blink.ThreadedLayoutWrite(m, s, bus);
            Require(m->ip == 0x123456789abcdef0UL && m->thread == -37 && m->tid == 0x1234 && m->blink_host_system == s);
            Require((int)Blink.Atomic.Load(ref m->attention) != 0 && (int)m->canhalt != 0 && (int)m->nofault != 0 && (int)m->insyscall != 0);
            Require(m->sysdepth == 3 && m->sigdepth == 4 && m->freelist.n == 5 && m->pagelocks.i == 6);
            Require(m->ctid == 0x1020304050L && m->fs.@base == 0x6172839405UL);
            byte* ax = Blink.GetModrmRegisterWordPointerRead8(m, 3UL << 22, 0, 0);
            for (int i = 0; i < 8; ++i) Require(ax[i] == 0x31 + i);
            Blink.blink_host_signal_jump_storage* jump = (Blink.blink_host_signal_jump_storage*)&m->onhalt;
            Require(jump->ordinary.words[0] == 0x9988776655443322UL && jump->mask_saved == 1 && m->spawn_sigmask.words[0] == 0x12345678);
            Require((int)s->loaded != 0 && (int)s->trapexit != 0 && s->exitcode == 33 && s->fds.list == &m->elem);
            Require(s->machines_cond == 11 && s->machines_lock == 12 && s->pagelocks_cond == 13 && s->pagelocks_lock == 14 && s->exec_lock == 15 && s->sig_lock == 16 && s->mmap_lock == 17);
            Require(bus->@lock[0] == 21 && bus->@lock[255] == 22 && bus->futexes.mem[0].addr == 0x1234000 && bus->futexes.mem[99].cond == 23);
            m->ip = 0xfedcba9876543210UL; m->thread = -73; m->tid = 0x4321; m->blink_host_system = s;
            Blink.Atomic.Store(ref m->attention, default); m->canhalt = false; m->nofault = false; m->insyscall = false;
            m->sysdepth = 7; m->sigdepth = 8; m->freelist.n = 9; m->pagelocks.i = 10;
            m->ctid = 0x5060708090L; m->fs.@base = 0x1728394056UL;
            for (int i = 0; i < 8; ++i) ax[i] = (byte)(0x51 + i);
            jump->ordinary.words[0] = 0x2233445566778899UL; jump->mask_saved = 0; m->spawn_sigmask.words[0] = 0x87654321;
            s->loaded = false; s->trapexit = false; s->exitcode = 44; s->fds.list = &m->elem;
            s->machines_cond = 31; s->machines_lock = 32; s->pagelocks_cond = 33; s->pagelocks_lock = 34; s->exec_lock = 35; s->sig_lock = 36; s->mmap_lock = 37;
            bus->@lock[0] = 41; bus->@lock[255] = 42; bus->futexes.mem[0].addr = 0x5678000; bus->futexes.mem[99].cond = 43;
            Require(Blink.ThreadedLayoutVerify(m, s, bus) == 0);
            GC.Collect(2, GCCollectionMode.Forced, true, true);
            Require(Blink.ThreadedLayoutVerify(m, s, bus) == 0);
        } finally { foreach (nint pointer in allocations) NativeMemory.AlignedFree((void*)pointer); }
    }
}
