<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <QuickJsProject Condition="'$(QuickJsProject)' == ''">$(MSBuildThisFileDirectory)../../generated/TranslatedQuickJs/TranslatedQuickJs.csproj</QuickJsProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(QuickJsProject)" />
  </ItemGroup>
</Project>
